---
- name: reload sysctl
  shell: "/sbin/sysctl -p"

- name: firewalld restart
  shell: "/usr/bin/firewall-cmd --reload"

- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart ntp
  service: 
    name: chronyd
    state: restarted

- name: restart syslog-ng
  service: 
    name: syslog-ng
    state: restarted
